# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Swift 6.0.0
      uses: fwal/setup-swift@v2
      with:
        swift-version: '6.0.0'
    - name: Cache Swift dependencies
      uses: actions/cache@v4
      with:
        path: |
          Package.resolved
          .build
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.swift', '**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
